version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: app
    restart: always
    env_file:
      - ./conf/.env.dev
    ports:
      - "8001:8000"
    depends_on:
      - app_db
    volumes:
      - ./logs:/app/logs

  app_db:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: app_db
    restart: always
    env_file:
      - ./conf/.env.db
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d

#  test_db:
#    image: mongo:5.0
#    container_name: test_db
#    restart: always
#    env_file:
#      ./conf/.env.test
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
#      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
#      - MONGO_INITDB_DATABASE=${DB_NAME}
#    ports:
#      - "27019:27017"
#    volumes:
#      - test_db_data:/data/db

volumes:
  db_data:
    driver: local
  db_config:
    driver: local


