version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: dictionary-words-app
    restart: always
    env_file:
      - ./conf/.env.dev
    ports:
      - "8001:8000"
    depends_on:
      - app_db
    volumes:
      - ./logs:/app/logs

  app_db:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: dictionary-words-db
    restart: always
    env_file:
      - ./conf/.env.db
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb

  test_app:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
    container_name: test-dictionary-words-app
    restart: "no"
    env_file:
      - ./conf/.env.test
    environment:
      - ENV=test
    depends_on:
      - test_db


  test_db:
    image: mongodb/mongodb-community-server:8.0-ubuntu2204
    container_name: dictionary-words-test-db
    restart: always
    env_file:
      - ./conf/.env.testdb
    ports:
      - "27019:27017"
    volumes:
      - test_db_data:/data/db
      - test_db_config:/data/configdb
      - ./reports:/app/reports

volumes:
  db_data:
    driver: local
  db_config:
    driver: local
  test_db_data:
    driver: local
  test_db_config:
    driver: local

